import { NextRequest, NextResponse } from 'next/server';

// Template-based prompt generator (no API needed)
function generatePrompt(category: string, objective: string, persona: string, targetModel: string, format: string, tone: number): string {
    const toneDescription = tone < 33 ? 'casual and friendly' : tone > 66 ? 'academic and strict' : 'professional and balanced';

    return `# Refined ${category} Prompt for ${targetModel}

## Role Assignment
You are acting as: **${persona}**

## Primary Objective
${objective}

## Context & Domain
This is a **${category}** task. Approach this with domain-specific knowledge and best practices.

## Output Requirements
- **Format**: ${format}
- **Tone**: ${toneDescription}
- **Target Model**: Optimized for ${targetModel}

## Instructions
1. Carefully analyze the objective in the context of ${category}
2. Provide a comprehensive, ${toneDescription} response
3. Structure your output according to the **${format}** format specification
4. Maintain consistency with ${targetModel}'s capabilities and strengths
5. Incorporate domain-specific terminology and frameworks relevant to ${category}

## Quality Criteria
- Clear, actionable, and well-structured guidance
- Appropriate level of technical depth for ${category}
- ${toneDescription.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} communication style
- Adherence to ${format} formatting standards

## Success Metrics
- Task completion aligns with stated objective
- Output demonstrates expert-level understanding of ${category}
- Communication style matches the requested ${toneDescription} tone

---
*Generated by RefineAI - Smart Prompt Engineering*
*Category: ${category} | Model: ${targetModel} | Format: ${format}*`;
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { category, objective, persona, targetModel, format, tone } = body;

        // Use template-based generation (reliable and fast)
        const refinedPrompt = generatePrompt(
            category || 'general task',
            objective || 'No objective specified',
            persona || 'expert assistant',
            targetModel || 'AI model',
            format || 'Markdown',
            tone || 50
        );

        return NextResponse.json({
            refinedPrompt,
            success: true,
            source: 'template'
        });

    } catch (error: any) {
        console.error('Generate Prompt Error:', error);

        return NextResponse.json(
            {
                error: 'Failed to generate prompt',
                details: error.message,
                success: false
            },
            { status: 500 }
        );
    }
}
